name: Auto Run Scenarios

on:
    pull_request:
      branches:
        - main

jobs:
  run-scenarios:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run scenarios
      env:
        API_BASE_URL: ${{ secrets.API_BASE_URL }}
        API_KEY: ${{ secrets.API_KEY }}
        AGENT_ID: "123"  # Replace with your agent ID
        SCENARIOS: "456,789,101"  # Replace with your scenario IDs
        FREQUENCY: "1"
        TIMEOUT: "1800"  # 30 minutes
        POLL_INTERVAL: "30"
      run: python run_scenarios.py
